[[podcasts]]
name = "起朱楼宴宾客"
feedUrl = "https://feed.xyzfm.space/ahng8d9qlywl"

[[podcasts]]
name = "Lightcone Podcast"
feedUrl = "https://anchor.fm/s/f58d3330/podcast/rss"

[[podcasts]]
name = "一席"
feedUrl = "https://feed.xyzfm.space/jq7xytwpykrg"
