name = "2025 Progress Tracker"
id = "1609782c-4f4a-81f6-b842-000be258762d"

[properties.Status]
type = "status"
options = [ "Not started", "In progress", "Done" ]

[properties.Tasks]
type = "select"
options = [
  "Family",
  "Career & Job",
  "Writing",
  "Project",
  "Career Event",
  "Skill/Hobby",
  "Book",
  "Music",
  "Activity (Offline)",
  "Entertainment (Online)",
  "Speical/Misc."
]

[properties.Date]
type = "date"

[properties.Task]
type = "title"
